USE GenesisResources;

CREATE TABLE Persons(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
	surname VARCHAR(100),
	personID VARCHAR(100) UNIQUE,
	uuid VARCHAR(100) UNIQUE
);

DELETE FROM Persons;

ALTER TABLE Persons AUTO_INCREMENT = 1;
