CREATE DATABASE GenesisResources;

USE GenesisResources;

CREATE TABLE Persons(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100),
	surname VARCHAR(100),
	personID VARCHAR(100) UNIQUE,
	uuid VARCHAR(100) UNIQUE
);

